### ISSUE TITLE
Naming and composability?

### ISSUE THREAD

**Issue by timholy** [eschnett/FastArrays.jl#1]
Leftover from https://github.com/JuliaLang/julia/issues/15648#issuecomment-205353238.

Clearly I'm late for bikeshedding the name, but I'm not sure that name conveys the way in which they are flexible...I keep thinking of [wobbly windows](https://www.youtube.com/watch?v=nbCg9_YgKgM)! I do think `OffsetArrays` is a better name, and wonder whether you could combine forces?

More importantly, this seems to combine the functionality of `OffsetArrays` and `FixedSizeArrays`. If `OffsetArrays` were implemented as a thin-wrapper around an arbitrary array type, wouldn't this be more composable?

**Comment by eschnett** [comment]
Thank you! I didn't dare publicly ask for a better name (http://goo.gl/mV9MvD) , and "Flexible" was just the best thing with which I could come up. I don't like the name myself either.

Much of the generated code depends on which dimensions have a fixed size and which don't, and which dimensions have a fixed lower bound and which don't. (It's flexible in this respect!) So the array length might or might not be fixed.

The particular use case I needed was an array where all lower bounds are `0` (for convenience), and where the first dimension is fixed, but the second is arbitrary, as in `(0:3, 0:*)`. This led to noticeable performance benefits in my application, which has inner loops that manipulate several arrays that each have several dimensions, some fixed, some not.

I looked at FixedSizeArrays and ImmutableArrays. Both are similar to FlexibleArrays, in the case of arrays with a fixed length. FixedSizeArrays seems to allow arbitrary choices for the underlying type -- a very neat idea, if the array length is fixed.

So maybe `OffsetArraysMaybeFixedLowerBoundMaybeFixedSizeMaybeFixedLengthMaybeImmutableArrays`...? Or maybe just `GenericArrays`. (Or `EmacsArrays`.)

**Comment by timholy** [comment]
`OffsetArraysMaybeFixedLowerBoundMaybeFixedSizeMaybeFixedLengthMaybeImmutableArrays` would certainly make everyone appreciate the wonders of tab completion. Let's go with that :wink:.

I hadn't properly appreciated just how flexible this all is, and I certainly shouldn't comment on implementation without understanding it better!

**Comment by eschnett** [comment]
Wait... I really don't like the current name, do you have a suggestion?

**Comment by timholy** [comment]
Maybe `CustomBoundsArrays`?

**Comment by timholy** [comment]
Or `UnrolledBoundsArrays`?
